import React from "react";

function SectionHeading({ children }) {
  return (
    <div className="border-b border-primary/30 pb-3 mb-5">
      <h2 className="text-2xl font-semibold text-black">{children}</h2>
    </div>
  );
}

function SubHeading({ children }) {
  return <h3 className="text-lg font-semibold text-black mb-2 mt-6">{children}</h3>;
}

function Para({ children }) {
  return <p className="text-md text-grey leading-relaxed">{children}</p>;
}

function Bullet({ children }) {
  return (
    <li className="flex gap-3 items-start text-md text-grey">
      <span className="shrink-0 mt-2 w-1.5 h-1.5 rounded-full bg-primary" />
      <span>{children}</span>
    </li>
  );
}

function NumberedItem({ number, title, children }) {
  return (
    <li className="flex gap-4 items-start">
      <span className="shrink-0 w-7 h-7 rounded-full bg-black text-primary font-semibold text-sm flex items-center justify-center mt-0.5">
        {number}
      </span>
      <p className="text-md text-grey">
        <span className="font-medium text-black">{title}: </span>
        {children}
      </p>
    </li>
  );
}

function CookieCard({ title, type, children }) {
  return (
    <div className="bg-white border border-primary/30 rounded-lg p-5">
      <p className="text-xs uppercase tracking-widest text-primary font-medium mb-3">{title}</p>
      <div className="space-y-1 text-md text-grey">
        <p><span className="font-medium text-black">Type:</span> {type}</p>
        <p><span className="font-medium text-black">Administered by:</span> Us</p>
        <p><span className="font-medium text-black">Purpose:</span> {children}</p>
      </div>
    </div>
  );
}

const page = () => {
  return (
    <>
      <header className="bg-white text-grey pt-12 px-6 text-center">
       
        <h1 className="text-4xl md:text-6xl font-bold leading-tight">Privacy Policy</h1>
        {/* <p className="text-primary mt-4 text-md font-light tracking-wide">
          Last updated: May 14, 2026
        </p> */}
      </header>

      <main className="max-w-7xl mx-auto px-6 py-14 space-y-12">

        <section className="space-y-4">
          <SectionHeading>Interpretation and Definitions</SectionHeading>
          <SubHeading>Interpretation</SubHeading>
          <Para>
            The words of which the initial letter is capitalized have meanings defined under the
            following conditions. The following definitions shall have the same meaning regardless
            of whether they appear in singular or in plural.
          </Para>
          <SubHeading>Definitions</SubHeading>
          <Para>For the purposes of this Privacy Policy:</Para>
          <ol className="space-y-3 mt-2">
            {[
              ["Account", "means a unique account created for You to access our Service or parts of our Service."],
              ["Affiliate", `means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.`],
              ["Company", `(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Looks Salon Pvt Ltd, No 17A/22, Ajmal Khan Road, Karol Bagh, New Delhi – 110 005.`],
              ["Cookies", "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses."],
              ["Country", "refers to: Delhi, India"],
              ["Device", "means any device that can access the Service such as a computer, a cellphone or a digital tablet."],
              ["Personal Data", "is any information that relates to an identified or identifiable individual."],
              ["Service", "refers to the Website."],
              ["Service Provider", "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used."],
              ["Third-party Social Media Service", "refers to any website or any social network website through which a User can log in or create an account to use the Service."],
              ["Usage Data", "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)."],
              ["Website", "refers to Looks Salon, accessible from www.lookssalon.in"],
              ["You", "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."],
            ].map(([term, def], i) => (
              <NumberedItem key={i} number={i + 1} title={term}>{def}</NumberedItem>
            ))}
          </ol>
        </section>

        <section className="space-y-4">
          <SectionHeading>Collecting and Using Your Personal Data</SectionHeading>

          <SubHeading>Types of Data Collected</SubHeading>

          <SubHeading>Personal Data</SubHeading>
          <Para>
            While using Our Service, We may ask You to provide Us with certain personally
            identifiable information that can be used to contact or identify You. Personally
            identifiable information may include, but is not limited to:
          </Para>
          <ul className="space-y-2 mt-2">
            {["Email address", "First name and last name", "Phone number", "Address, State, Province, ZIP/Postal code, City", "Usage Data"].map((item, i) => (
              <Bullet key={i}>{item}</Bullet>
            ))}
          </ul>

          <SubHeading>Usage Data</SubHeading>
          <div className="space-y-3">
            <Para>Usage Data is collected automatically when using the Service.</Para>
            <Para>
              Usage Data may include information such as Your Device&apos;s Internet Protocol address
              (e.g. IP address), browser type, browser version, the pages of our Service that You
              visit, the time and date of Your visit, the time spent on those pages, unique device
              identifiers and other diagnostic data.
            </Para>
            <Para>
              When You access the Service by or through a mobile device, We may collect certain
              information automatically, including, but not limited to, the type of mobile device
              You use, Your mobile device unique ID, the IP address of Your mobile device, Your
              mobile operating system, the type of mobile Internet browser You use, unique device
              identifiers and other diagnostic data.
            </Para>
            <Para>
              We may also collect information that Your browser sends whenever You visit our Service
              or when You access the Service by or through a mobile device.
            </Para>
          </div>

          <SubHeading>Information from Third-Party Social Media Services</SubHeading>
          <Para>
            The Company allows You to create an account and log in to use the Service through the
            following Third-party Social Media Services:
          </Para>
          <ul className="space-y-2 mt-2">
            {["Google", "Facebook", "Twitter", "LinkedIn"].map((item, i) => (
              <Bullet key={i}>{item}</Bullet>
            ))}
          </ul>
          <div className="space-y-3 mt-3">
            <Para>
              If You decide to register through or otherwise grant us access to a Third-Party Social
              Media Service, We may collect Personal data that is already associated with Your
              Third-Party Social Media Service&apos;s account, such as Your name, Your email address,
              Your activities or Your contact list associated with that account.
            </Para>
            <Para>
              You may also have the option of sharing additional information with the Company through
              Your Third-Party Social Media Service&apos;s account. If You choose to provide such
              information and Personal Data, during registration or otherwise, You are giving the
              Company permission to use, share, and store it in a manner consistent with this
              Privacy Policy.
            </Para>
          </div>

          <SubHeading>Tracking Technologies and Cookies</SubHeading>
          <Para>
            We use Cookies and similar tracking technologies to track the activity on Our Service
            and store certain information. Tracking technologies used are beacons, tags, and scripts
            to collect and track information and to improve and analyze Our Service. The technologies
            We use may include:
          </Para>
          <ul className="space-y-3 mt-3">
            <Bullet>
              <strong className="text-black">Cookies or Browser Cookies.</strong> A cookie is a
              small file placed on Your Device. You can instruct Your browser to refuse all Cookies
              or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You
              may not be able to use some parts of our Service.
            </Bullet>
            <Bullet>
              <strong className="text-black">Web Beacons.</strong> Certain sections of our
              Service and our emails may contain small electronic files known as web beacons (also
              referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company
              to count users who have visited those pages or opened an email and for other related
              website statistics.
            </Bullet>
          </ul>
          <div className="space-y-3 mt-3">
            <Para>
              Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on
              Your personal computer or mobile device when You go offline, while Session Cookies are
              deleted as soon as You close Your web browser.
            </Para>
            <Para>We use both Session and Persistent Cookies for the purposes set out below:</Para>
          </div>
          <div className="space-y-4 mt-4">
            <CookieCard title="Necessary / Essential Cookies" type="Session Cookies">
              These Cookies are essential to provide You with services available through the Website
              and to enable You to use some of its features. They help to authenticate users and
              prevent fraudulent use of user accounts.
            </CookieCard>
            <CookieCard title="Cookies Policy / Notice Acceptance Cookies" type="Persistent Cookies">
              These Cookies identify if users have accepted the use of cookies on the Website.
            </CookieCard>
            <CookieCard title="Functionality Cookies" type="Persistent Cookies">
              These Cookies allow us to remember choices You make when You use the Website, such as
              remembering your login details or language preference, to provide a more personal
              experience.
            </CookieCard>
          </div>
          <Para>
            For more information about the cookies we use and your choices regarding cookies, please
            visit our Cookies Policy or the Cookies section of our Privacy Policy.
          </Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Use of Your Personal Data</SectionHeading>
          <Para>The Company may use Personal Data for the following purposes:</Para>
          <ol className="space-y-4 mt-2">
            <NumberedItem number={1} title="To provide and maintain our Service">including to monitor the usage of our Service.</NumberedItem>
            <NumberedItem number={2} title="To manage Your Account">to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service available to You as a registered user.</NumberedItem>
            <NumberedItem number={3} title="For the performance of a contract">the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</NumberedItem>
            <NumberedItem number={4} title="To contact You">by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including security updates.</NumberedItem>
            <NumberedItem number={5} title="To provide You">with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about, unless You have opted not to receive such information.</NumberedItem>
            <NumberedItem number={6} title="To manage Your requests">To attend and manage Your requests to Us.</NumberedItem>
            <NumberedItem number={7} title="For business transfers">We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</NumberedItem>
            <NumberedItem number={8} title="For other purposes">such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</NumberedItem>
          </ol>
        </section>

        <section className="space-y-4">
          <SectionHeading>Sharing Your Personal Data</SectionHeading>
          <Para>We may share Your personal information in the following situations:</Para>
          <ul className="space-y-3 mt-2">
            <Bullet><span className="text-black font-medium">With Service Providers:</span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</Bullet>
            <Bullet><span className="text-black font-medium">For business transfers:</span> We may share or transfer Your personal information in connection with any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</Bullet>
            <Bullet><span className="text-black font-medium">With Affiliates:</span> We may share Your information with Our affiliates, including Our parent company and any subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</Bullet>
            <Bullet><span className="text-black font-medium">With business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</Bullet>
            <Bullet><span className="text-black font-medium">With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</Bullet>
            <Bullet><span className="text-black font-medium">With Your consent:</span> We may disclose Your personal information for any other purpose with Your consent.</Bullet>
          </ul>
        </section>

        <section className="space-y-4">
          <SectionHeading>Retention of Your Personal Data</SectionHeading>
          <Para>
            The Company will retain Your Personal Data only for as long as is necessary for the
            purposes set out in this Privacy Policy. We will retain and use Your Personal Data to
            the extent necessary to comply with our legal obligations, resolve disputes, and enforce
            our legal agreements and policies.
          </Para>
          <Para>
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is
            generally retained for a shorter period of time, except when this data is used to
            strengthen the security or improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Transfer of Your Personal Data</SectionHeading>
          <Para>
            Your information, including Personal Data, is processed at the Company&apos;s operating
            offices and in any other places where the parties involved in the processing are located.
            It means that this information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other governmental jurisdiction
            where the data protection laws may differ from those of Your jurisdiction.
          </Para>
          <Para>
            Your consent to this Privacy Policy followed by Your submission of such information
            represents Your agreement to that transfer.
          </Para>
          <Para>
            The Company will take all steps reasonably necessary to ensure that Your data is treated
            securely and in accordance with this Privacy Policy and no transfer of Your Personal Data
            will take place to an organization or a country unless there are adequate controls in place.
          </Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Delete Your Personal Data</SectionHeading>
          <Para>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</Para>
          <Para>Our Service may give You the ability to delete certain information about You from within the Service.</Para>
          <Para>You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</Para>
          <Para>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Disclosure of Your Personal Data</SectionHeading>
          <SubHeading>Business Transactions</SubHeading>
          <Para>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</Para>
          <SubHeading>Law Enforcement</SubHeading>
          <Para>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</Para>
          <SubHeading>Other Legal Requirements</SubHeading>
          <Para>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</Para>
          <ul className="space-y-2 mt-2">
            {[
              "Comply with a legal obligation",
              "Protect and defend the rights or property of the Company",
              "Prevent or investigate possible wrongdoing in connection with the Service",
              "Protect the personal safety of Users of the Service or the public",
              "Protect against legal liability",
            ].map((item, i) => <Bullet key={i}>{item}</Bullet>)}
          </ul>
        </section>

        <section className="space-y-4">
          <SectionHeading>Security of Your Personal Data</SectionHeading>
          <Para>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Children&apos;s Privacy</SectionHeading>
          <Para>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</Para>
          <Para>If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</Para>
          <Para>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.</Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Links to Other Websites</SectionHeading>
          <Para>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</Para>
          <Para>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Changes to this Privacy Policy</SectionHeading>
          <Para>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</Para>
          <Para>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</Para>
          <Para>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</Para>
        </section>

        <section className="space-y-4">
          <SectionHeading>Contact Us</SectionHeading>
          <Para>If you have any questions about this Privacy Policy, You can contact us:</Para>
          <div className="bg-black text-[#FAF6F0] rounded-xl p-6 space-y-3 mt-2">
            <div className="flex items-center gap-3">
              <svg className="w-4 h-4 text-primary shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <a href="mailto:customercare@lookssalon.in" className="text-md text-primary hover:underline">
                customercare@lookssalon.in
              </a>
            </div>
            <div className="flex items-center gap-3">
              <svg className="w-4 h-4 text-primary shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
              <span className="text-md text-[#FAF6F0]/80">+91-11-28751520, +91-11-41061400</span>
            </div>
          </div>
        </section>

      </main>
    </>
  );
};

export default page;
